apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/stripe-cli.yaml
  - service-overrides.yaml

secretGenerator:
  - name: backend-env
    envs:
      - backend.env