export enum ValidationErrorType {
    EXPIRED = "EXPIRED",
    BAD_REQUEST = "BAD_REQUEST"
}

export enum AuthErrorCode {
    UNAUTHENTICATED = "UNAUTHENTICATED",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    INVALID_TOKEN = "INVALID_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
}