apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-cli
  labels:
    app: stripe-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stripe-cli
  template:
    metadata:
      labels:
        app: stripe-cli
    spec:
      containers:
      - name: stripe-cli-container
        image: stripe/stripe-cli:latest
        command: ["/bin/sh", "-c"]
        args:
          - >
            stripe listen 
            --forward-to backend-service:3001/api/payments/webhook 
            --api-key $(STRIPE_SECRET_KEY)
        env:
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-env
              key: STRIPE_SECRET_KEY